male(kuru).
male(parashara).
male(shantanu).
male(vyasa).
male(vidura).
male(dhritrashtra).
male(pandu).
male(vasudeva).
male(duryodhana).
male(nakula).
male(sahadeva).
male(arjuna).
male(bhima).
male(yudhisthira).
male(karna).
male(satanika).
male(srutasena).
male(srutakarman).
male(abhimanyu).
male(iravan).
male(babruvahana).
male(sutasoma).
male(ghatotchkacha).
male(prativindhya).
male(parikshit).
male(janamejaya).
male(krishna).
female(ganga).
female(satyavati).
female(ambika).
female(amba).
female(ambalika).
female(poorna).
female(madri).
female(gandhari).
female(kunti).
female(devaki).
female(dussala).
female(rukmini).
female(draupadi).
female(subhadra).
female(ulupi).
female(chitrangda).
female(vrishali).
female(hidimba).
female(uttara).
female(madravti).
female(vapushtama).
married(dhritrashtra,gandhari).
married(pandu,kunti).
married(pandu,madri).
married(vasudeva,devaki).
married(nakula,draupadi).
married(sahadeva,draupadi).
married(arjuna,draupadi).
married(arjuna,subhadra).
married(arjuna,ulupi).
married(arjuna,chitrangda).
married(bhima,draupadi).
married(bhima,hidimba).
married(yudhisthira,draupadi).
married(abhimanyu,uttara).
married(parikshit,madravti).
married(janamejaya,vapushtama).
married(shantanu,ganga).
married(vyasa,voorna).
married(parashara,satyavati).
